edge/wiotp/cpu2wiotp/Dockerfile.arm, edge/wiotp/cpu2wiotp/Dockerfile.x86, edge/wiotp/cpu2wiotp/Makefile, edge/wiotp/cpu2wiotp/horizon/cpu2wiotp-amd64.json, edge/wiotp/cpu2wiotp/horizon/cpu2wiotp-arm.json, edge/wiotp/cpu2wiotp/horizon/pattern/cpu2wiotp.json, edge/wiotp/cpu2wiotp/workload.sh
- added `-S -w %{http_code}` to curl cmd to get errors
- added checking of http code
- protected some of the mosquitto_pub args in quotes
- added `make publish` target, since we aren't supposed to tag docker images right now (current limitation in mike's docker pull code
- added building for different arch
- updated cpu2wiotp workload and pattern def files to point to version 1.1.4
=> fix cpu2wiotp error and build improvements

edge/services/cpu_percent/Dockerfile.amd64, edge/services/cpu_percent/Makefile, edge/services/cpu_percent/horizon/README.md, edge/services/cpu_percent/horizon/cpu-template.json, edge/wiotp/cpu2wiotp/Dockerfile.amd64, edge/wiotp/cpu2wiotp/Makefile, edge/wiotp/cpu2wiotp/horizon/README.md, edge/wiotp/cpu2wiotp/horizon/cpu2wiotp-template.json, edge/wiotp/cpu2wiotp/horizon/pattern/cpu2wiotp-template.json
Changed the naming of the docker images from x86 to amd64, so we could have just one arch env var in the quick start guide, and reduce confusion.
=> Change to amd64

edge/msghub/cpu2msghub/horizon/pattern/cpu2msghub.json, edge/msghub/cpu2msghub/horizon/service.definition.json, edge/msghub/cpu2msghub/horizon/userinput.json, edge/msghub/sdr2msghub/horizon/pattern/sdr2msghub.json, edge/msghub/sdr2msghub/horizon/service.definition.json, edge/msghub/sdr2msghub/horizon/userinput.json
The rationale for these changes was to best handle these use cases:
1) **User:** following adding-your-machine, HZN_ORG_ID=cgiroua@us.ibm.com, they register their node with IBM/cpu2msghub pattern
1) userinput.json: cpu2msghub org hardcoded to IBM, sdr & gps orgs hardcoded to IBM or sections omitted
2) cpu2msghub.json (pattern): will be used by ibm edge fabric dev to predefine pattern in IBM org, so doesn't matter which way
3) service.definition.json: will be used by ibm edge fabric dev to predefine cpu2msghub service in IBM org, so doesn't matter which way
2) **Service Developer:** following dev guide, copy cpu2msghub service def, change service url, create service in cgiroua@us.ibm.com org, copy cpu2msghub pattern to cgiroua@us.ibm.com org and change to reference their service
1) …
=> small changes in whether to use IBM or HZN_ORG_ID in poc metadata

edge/services/gps/Dockerfile.amd64.test, edge/services/gps/Dockerfile.arm.test, edge/services/gps/Makefile, edge/services/gps/horizon/envvars.sh.sample, edge/services/gps/src/hgps/hgps.go
Added an infinite retry loop on ifconfig.co (cannot really work without it);
added infinite retry loop on api.ipstack.com (same deal, we need it, so it should have had retries too);
both of the above steps log status during retries and state results when successful;
fixed a minor issue that was suppressing debug output;
also fixed some Makefile issues that had broken the test suite, and
I ran 'go fmt' on hgps.go which caused some whitespace changes, sorry.
I also bumped the version in gps/horizon/envvars.sh.sample
Ran test suite for 300000+ stress tests.
Manually tested bad addresses for ifconfig.co and api.ipstack.com to simulate error responses, and also tested with all different levels of debug output enables.
PLEASE NOTE: IMO this PR should not be merged until after demos are over …
=> Fixing issue #115, and more.

edge/services/sdr/Makefile
Forgot to add new flag for `hzn exchange service publish` to have sdr pull and overwrite if there is an existing version already in the exchange
=> SDR Makefile Update

edge/evtstreams/cpu2evtstreams/CreateService.md, edge/evtstreams/cpu2evtstreams/README.md, edge/services/helloworld/README.md, tools/edgeDeviceFiles.sh
edgeDeviceFiles:
- added the `-k` flag to create an API Key even if one is found with `$USER-Api-Key` name 
- changed env var from ICP_URL to CLUSTER_URL 
- added `-f` flag to move files to specified directory. I create it if it does not exist. 
- updated to use 4.0.0 tar file
Samples:
- some small readme updated based on some things I talked about with Parisa when we were walking thru what some uses will do next round of testing
=> Edge device files script & small README updates

tools/edgeDeviceFiles.sh
We've changed the PPA package name.
Also added the ability to use `-d stretch` for the older raspbian stretch image. It now defaults to `buster`
=> update device installation content file name & add support for buster

tools/edgeDeviceFiles.sh
- changed agent-install.sh to target v4.0 branch 
- added usage info about -d and 32-bit-ARM device
=> edgeDeviceFiles updates (v4.0 branch, usage comments)

tools/exchangePublishScript.sh
1-line fix to `exchangePublishScript.sh`: the path for `examples/tools/blessedSamples.txt` should not have `$(dirname $0)` at the beginning, because the examples repo is cloned in the current directory.
This only came up because i was running exchangePublishScript.sh in my local exchange environment, so i don't think you need to put this fix in the `v4.0` branch, just `master`. But please do verify that it still works when run for a real cluster.
=> fix path of blessedSamples in exchangePublishScript

tools/edgeNodeFiles.sh
- The problem on mac was the cmd to restart docker returns before docker is ready, so added polling to wait till ready
- Removed the node id from `agent-install.cfg` so the tar file can be used for many edge clusters
=> Issue 328: fixed edgeNodeFiles.sh on mac and removed node id from tar file

tools/edgeNodeFiles.sh
- The line `IMAGE_TAR_FILE="amd64_anax_k8s_ubi.tar"` was misleading, because it made it look like we were using the ubi agent image (which is now out of date because we are no longer building it). I removed `_ubi` to make it more obvious.
- Cleaned up the usage info
- Change variable `EDGE_NODE` to `EDGE_NODE_TYPE` to make the code more readable.
=> update IMAGE_TAR_FILE and clean up usage info

edge/services/helloMMS/README.md, edge/services/operator/simple-operator/deploy/horizon/pattern.json
Before I implement the method of adding the two fields to the `hzn.json` file Lily mentioned she couldn't see the `operator` pattern and I realized it's `public: false` currently
=> Quick fix for operator pattern public = true 

edge/evtstreams/cpu2evtstreams/README.md
[1cec1c3](https://github.com/open-horizon/examples/commit/1cec1c3c2e55674a982a87da25ab326fc0d45cec) removed unnecessary commands in the Readme, but additionally removed the command to the get the user input file, which is still necessary. 
=> Readd command to get user input file in cpu2evtstreams

edge/evtstreams/cpu2evtstreams/service.sh, edge/evtstreams/sdr2evtstreams/main.go, edge/services/cpu_percent/Dockerfile.amd64, edge/services/cpu_percent/Dockerfile.arm, edge/services/cpu_percent/Dockerfile.arm64, edge/services/cpu_percent/README.md, edge/services/cpu_percent/horizon/hzn.json, edge/services/cpu_percent/start.sh, edge/services/gps/Dockerfile.amd64, edge/services/gps/Dockerfile.arm, edge/services/gps/Dockerfile.arm64, edge/services/gps/README.md, edge/services/gps/horizon/hzn.json, edge/services/gps/horizon/service.definition.json, edge/services/gps/src/main.go, edge/services/sdr/Dockerfile.amd64, edge/services/sdr/Dockerfile.arm, edge/services/sdr/Dockerfile.arm64, edge/services/sdr/README.md, edge/services/sdr/bbcfake/bbcfake.go, edge/services/sdr/horizon/hzn.json, edge/services/sdr/main.go, edge/services/sdr/rtlsdrclientlib/clientlib.go, tools/curlServiceTest.sh
Closes #349
This commit changes the `gps`, `cpu_percent`, and `sdr` examples to run as nonroot, following the example of `helloworld` sample service.
Tested by making sure that updated services continued to function as normal, as well as the services that use these lower level services, such as `sdr2evtstreams` and `cpu2evtstreams`.
Note: there was also a bug that caused the `sdr` service to not return audio, because the link in the regex didn’t match up with the link we were using to get the audio. To properly test `sdr`, I've included that small fix in the `bbcfake.go` file. We also removed instances of `jq .` in the readmes for `cpu_percent` and `gps`, because `jq` is no longer included in those containers. Thanks @t-fine for finding both bugs!
Signed-off-by: Clement Ng …
=> Change lower level services to run as nonroot

edge/evtstreams/cpu2evtstreams/CreateService.md, edge/evtstreams/cpu2evtstreams/Makefile, edge/evtstreams/cpu2evtstreams/horizon/service.definition.json, edge/evtstreams/sdr2evtstreams/CreateService.md, edge/evtstreams/sdr2evtstreams/horizon/service.definition.json, edge/evtstreams/watson_speech2text/CreateService.md, edge/evtstreams/watson_speech2text/horizon/service.definition.json, edge/services/audio2text/horizon/service.definition.json, edge/services/cpu_percent/Makefile, edge/services/cpu_percent/horizon/service.definition.json, edge/services/gps/Makefile, edge/services/gps/horizon/service.definition.json, edge/services/helloMMS/CreateService.md, edge/services/helloMMS/Makefile, edge/services/helloMMS/horizon/service.definition.json, edge/services/helloworld/Makefile, edge/services/helloworld/horizon/service.definition.json, edge/services/hotword_detection/horizon/service.definition.json, edge/services/mqtt2kafka/horizon/service.definition.json, edge/services/mqtt_broker/horizon/service.definition.json, edge/services/nginx-operator/Makefile, edge/services/nginx-operator/horizon/service.definition.json, edge/services/pi3_streamer/horizon/microservice.definition.json, edge/services/processtext/CreateService.md, edge/services/processtext/horizon/service.definition.json, edge/services/sdr/horizon/service.definition.json, edge/services/stopword_removal/horizon/service.definition.json, edge/services/text2speech/horizon/service.definition.json, edge/services/voice2audio/horizon/service.definition.json, edge/services/weatherstation/horizon/microservice.definition.json
Partially addresses #356 
This commit removes the "public" field from the service definition files of the up-to-date services. As discussed in this [comment](https://github.com/open-horizon/examples/issues/356#issuecomment-731166634), the "public" field should be moved out of the service definition files since it isn't tied tightly to the service image implementation. Instead, the "public" field will be set by a flag set by the `hzn exchange publish service` command instead. 
To make sure the changes are backwards compatible, there's an instruction in the README's to set the examples branch equal to the user's horizon CLI branch. To ensure that the `exchangePublish.sh` script continues functioning as normal, I've updated the `publish-only` Makefile targets of the `blessedSamples` to use …
=> Remove "public" field from services

cloud/sdr/ui/sdr-app/client/package-lock.json, cloud/sdr/ui/sdr-app/client/package.json
Ran `npm audit` and suggested fix `npm update elliptic --depth 5` for `elliptic`. I updated the semver rule for `react-dev-utils` because otherwise it would be locked on version `5.x.x`.
=> Update elliptic and react-dev-utils

cloud/sdr/deploy/ibm/README.md
The existing link is dead, so I changed it to a live link that talks about Creating an API key as an IBM cloud user.
=> Replace deprecated link to create user API key in sdr docs

edge/services/sdr/README.md
Now, users can listen to the audio on devices that don't support `aplay`, like Mac.
=> Update sdr docs with instructions for listening to audio with the play command

tools/loadResources
Signed-off-by: Doug Larson <larsond@us.ibm.com>
Inflating the clusterDeployment field called the utility to fail for edge cluster services. 
Resolved that issue by leaving that field as a string
=> Fix problem with edge cluster service

edge/services/sdr/Dockerfile.amd64, edge/services/sdr/Dockerfile.arm, edge/services/sdr/Dockerfile.arm64
Remove the branch checkout instruction from the sdr Dockerfiles, since I've merged the `rpc` branch into the `master` branch in my [librtlsdr](https://github.com/clementkng/librtlsdr/commit/e5e5a1d384da288f1bdce39d5ecaaced148ea93d) fork.
Tested that service still functions as expected.
=> Remove branch checkout instruction

cloud/sdr/ui/sdr-app/.gitignore
Fixes #495
Ensures that eclipse project files will not be pushed.
=> Add eclipse files to gitignore

edge/services/cpu_percent/horizon/service.definition.json, edge/services/gps/horizon/service.definition.json
Exposed ports through `edge/services/cpu_percent/horizon/service.definition.json` and `edge/services/gps/horizon/service.definition.json`. Port number is 8080 for both services. 
Fixes issue #555 : CPU_PERCENT and GPS examples do not expose port.
=> Issue 555 : CPU_PERCENT and GPS examples do not expose port

edge/services/nginx-operator/Makefile, edge/services/nginx-operator/horizon/pattern-all-arches.json
These modifications to the Makefile target `publish-only` will allow `exchangePublish.sh` to now load an exchange with the `ppc64le` arch version of the `ibm.nginx-operator` service.
=> feat: 424 publish operator example to ppc64le

edge/evtstreams/sdr2evtstreams/train/label/main.go
When a resource is given a permissions setting that provides access to a wider range of actors than required, it could lead to the exposure of sensitive information, or the modification of that resource by unintended parties. This is especially dangerous when the resource is related to program configuration, execution or sensitive user data.
=>  Issue open-horizon#173 fix CWE-732: Insecure File Permissions
