open-horizon/examples

edge/services/sdr/data_broker/Dockerfile.arm, edge/services/sdr/data_broker/main.go
- Remove line of dead code in Dockerfile.arm
- data_broker will now capture more frequently from good stations
=> SDR PoC: data broker basic multi-armed bandit

cloud/sdr/ui/sdr-app/app.js, cloud/sdr/ui/sdr-app/client/package-lock.json, cloud/sdr/ui/sdr-app/client/package.json, cloud/sdr/ui/sdr-app/client/src/App.js, cloud/sdr/ui/sdr-app/client/src/components/MapMarkerPopup.js, cloud/sdr/ui/sdr-app/client/src/containers/EdgeNodeDetails.js, cloud/sdr/ui/sdr-app/server/resolvers-node-postgres/index.js
- put in `query-string` lib since `react-router` no longer supports query parameters
- do ordering by `numberofmentions desc`, then by `timeupdated` desc
=> Sdr ui sprint2 wrapup

edge/msghub/sdr2msghub/Makefile, edge/msghub/sdr2msghub/audiolib/audiolib.go, edge/msghub/sdr2msghub/main.go, edge/services/sdr/Dockerfile.amd64, edge/services/sdr/Dockerfile.arm, edge/services/sdr/Dockerfile.arm64, edge/services/sdr/Makefile, edge/services/sdr/bbcfake/bbcfake.go, edge/services/sdr/main.go, edge/services/sdr/rtlsdrclientlib/clientlib.go
- Now pulls fake audio from BBC news
- Better logging
=> Dynamic mock audio

cloud/sdr/deploy/ibm/Makefile, cloud/sdr/deploy/ibm/README.md, cloud/sdr/deploy/ibm/deploy.sh
added automation for the SDR PoC cloud part deployment on IBM Cloud
=> added automation for the SDR PoC cloud part deployment

cloud/sdr/deploy/ibm/deploy.sh
Fix for issue https://github.com/open-horizon/examples/issues/133
=> Fix deploy script being stopped if grep does not find matching

cloud/sdr/deploy/ibm/deploy.sh
=> added a small fix with : missed

edge/services/helloworld/service.sh
Small change to helloworld for test PR
=> test update/commit of helloworld

edge/msghub/cpu2msghub/Makefile, edge/msghub/cpu2msghub/horizon/hzn.json, edge/msghub/cpu2msghub/horizon/service.definition.json, edge/services/cpu_percent/Makefile, edge/services/gps/Dockerfile.arm, edge/services/gps/Dockerfile.arm64, edge/services/gps/Makefile, edge/services/gps/horizon/hzn.json, edge/services/gps/src/main.go, edge/services/helloworld/Makefile, tools/blessedSamples.txt, tools/exchangePublishScript.sh
New makefile targets for script, added script to tools along with blessed samples, gps dockerfiles updated to cross-compile, gps main.go modified to not restart when it cant find hardware, deleted old commit with wrong changes.
=> Example updates

cloud/sdr/data-processing/ibm-functions/actions/package-lock.json, cloud/sdr/ui/sdr-app/client/package-lock.json, cloud/sdr/ui/sdr-app/package-lock.json, cloud/sdr/ui/sdr-app/package.json
fixed sdr npm module security alerts due to outdated versions
=> Addressed sdr vulnerabilities 

edge/msghub/cpu2msghub/Makefile, edge/msghub/cpu2msghub/horizon/hzn.json, edge/msghub/cpu2msghub/service.sh
Fixed syntax error when cpu2msghub can't yet reach the cpu service. See connected issue for details.
=> Cpu2msghub timeout

edge/evtstreams/cpu2evtstreams/README.md, edge/evtstreams/sdr2msghub/README.md, edge/evtstreams/watson_speech2text/README.md, edge/services/helloworld/README.md, edge/services/processtext/README.md, edge/services/sdr/README.md
Updates to the sample README's based on the info Parisa gathered from her research.
=> Updates to sample README's 

tools/edgeDeviceFiles.sh
Added commands to print, more verbose output, usage to a function, etc.
=> Gather files for agent-install script 

edge/evtstreams/cpu2evtstreams/PolicyRegister.md, edge/evtstreams/cpu2evtstreams/README.md, edge/evtstreams/cpu2evtstreams/horizon/business_policy.json, edge/evtstreams/cpu2evtstreams/horizon/node_policy.json, edge/services/gps/horizon/node_policy_privileged.json
- updates based on Parisa's comments
- updated the policy instructions to be consistent with helloworld
- added the userInput variables to the business policy file to be consistent with what Dave mentioned and not setting con gif variables directly on the node, but instead with the deployment policy 
- added `allowPrivileged: true` to `node_policy.json` so the policy can deploy
=> Cpu2es readme updates

edge/evtstreams/cpu2evtstreams/PolicyRegister.md, edge/evtstreams/cpu2evtstreams/horizon/business_policy.json, edge/services/helloworld/PolicyRegister.md, edge/services/helloworld/horizon/business_policy.json
- could be a temporary fix until I can work in a possible `$SERVICE_ORG` variable to `hzn.json`
=> Fix to business policy files 

edge/services/operator/simple-operator/deploy/horizon/service.definition.json, tools/exchangePublishScript.sh
- also update path to the operator tar file in the the service.defintion.json file
=> update exchangePublishScript to clone the v4.1 branch

edge/services/helloMMS/CreateService.md, edge/services/helloMMS/README.md
- have the user open a new terminal to view the logs as opposed to viewing the logs in the terminal they've been working in, then having to deal with all the possible unset env vars
=> helloMMS doc flow update

cloud/sdr/ui/sdr-app/package-lock.json, cloud/sdr/ui/sdr-app/package.json
=> Update object-path and node-fetch

edge/services/helloworld/Dockerfile.ppc64le, edge/services/helloworld/Makefile, edge/services/helloworld/horizon/pattern-all-arches.json
Signed-off-by: Dmitry Gorbachev <dmitry.gorbachev@ru.ibm.com>
Resolves #385
=> Issue 385 - ppc64le arch support for Helloworld service

tools/democmds.sh
Signed-off-by: Bruce Potter <bp@us.ibm.com>
=> add color prompt to democmds.sh

.travis.yml
=> update hzn cli install in travis file

edge/services/gps/Dockerfile.amd64, edge/services/gps/Dockerfile.arm, edge/services/gps/Dockerfile.arm64
=> bumped go version in GPS service Dockerfiles to 1.15

edge/services/nginx-operator/horizon/service.policy.json
=> removing single quotes from list of string service policy constraint

.github/workflows/pr-test.yml, edge/services/mqtt2kafka/Makefile, tools/curlServiceTest.sh, tools/serviceTest.sh
Also updated scripts to work with GitHub Actions environment
Signed-off-by: Ben Courliss <bencourliss@ibm.com>
=> Added GitHub Action to build pull requests.

edge/services/helloSecretWorld/Dockerfile.amd64, edge/services/helloSecretWorld/Dockerfile.arm, edge/services/helloSecretWorld/Dockerfile.arm64, edge/services/helloSecretWorld/Makefile, edge/services/helloSecretWorld/horizon/.gitignore, edge/services/helloSecretWorld/horizon/hzn.json, edge/services/helloSecretWorld/horizon/pattern-all-arches.json, edge/services/helloSecretWorld/horizon/pattern.json, edge/services/helloSecretWorld/horizon/service.definition.json, edge/services/helloSecretWorld/service.sh
Signed-off-by: Isabel Gan <Isabel.Gan@ibm.com>
=> Issue 2592 (anax) - Create sample service that uses secrets manager

edge/services/helloSecretWorld/CreateService.md, edge/services/helloSecretWorld/MaintainHW.md, edge/services/helloSecretWorld/README.md, edge/services/helloSecretWorld/horizon/deployment.policy.json, edge/services/helloSecretWorld/horizon/hw_who, edge/services/helloSecretWorld/horizon/pattern-all-arches.json, edge/services/helloSecretWorld/horizon/pattern.json, edge/services/helloSecretWorld/service.sh
Signed-off-by: Isabel Gan <Isabel.Gan@ibm.com>
=> Issue 2700 (anax) - Add documentation to the secrets example service

tools/blessedSamples.txt
Signed-off-by: Isabel Gan <Isabel.Gan@ibm.com>
=> Add helloSecretWorld example to blessed samples

edge/services/helloSecretWorld/horizon/pattern-all-arches.json
=> Add all arches to secretBinding in pattern-all-arches file

tools/loadResources
Signed-off-by: Doug Larson <larsond@us.ibm.com>
=> Support policies and patterns with spaces

edge/services/helloMMS/CreateService.md, edge/services/helloMMS/README.md, edge/services/helloMMS/object.json
=> updates to the helloMMS README/CreateService md files

edge/evtstreams/cpu2evtstreams/CreateService.md, edge/evtstreams/sdr2evtstreams/CreateService.md, edge/evtstreams/watson_speech2text/CreateService.md, edge/services/helloMMS/CreateService.md, edge/services/helloSecretWorld/CreateService.md, edge/services/helloSecretWorld/README.md, edge/services/helloworld/CreateService.md
- addressed some issue in helloSecretWorld related to only have one all arch pattern
- added `git checkout` to tag step to the rest of the top level services
- changed all  CreateService files to use `hzn dev service log`
=> Readme and CreateService tweaks

cloud/sdr/ui/sdr-app/client/src/config/settings.js.bak
=> Remove settings.js.bak file

cloud/sdr/ui/sdr-app/server/config/settings.js.bak
=> Remove server/config/settings.js.bak file

cloud/sdr/deploy/ibm/README.md
Adding note about depricating sdr cloud service and a branch name to deploy README
=> Note about soon deprecated cloud sdr example.

edge/services/nginx-operator/README.md, edge/services/nginx-operator/horizon/deployment.policy.json, edge/services/nginx-operator/horizon/node.policy.json
Signed-off-by: Doug Larson <larsond@us.ibm.com>
=> Update nginx-operator properties/constraints

edge/services/nginx-operator/CreateService.md, edge/services/nginx-operator/PatternRegister.md, edge/services/nginx-operator/README.md
Signed-off-by: John Walicki <johnwalicki@gmail.com>
Fixes #578
=> Issue #578 - Format operator example markdown files

edge/services/cpu_percent/horizon/hzn.json, edge/services/gps/horizon/hzn.json
Before closing issue https://github.com/open-horizon/examples/issues/555 I wanted to inclement the version, build and push both `CPU_PERCENT` and `GPS`
=> feat: 555 increase version of cpu and gps
